version: '3'

services:
  app:
    build: .
    container_name: ramen_app
    environment:
      - DB_DRIVER=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=ramen
      - WEB_SERVER_PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    restart: always
    networks:
        - ramen_network


  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ramen
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - ramen_network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d

networks:
  ramen_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local