### GET request to list all broths
GET http://localhost:8000/broths HTTP/1.1
x-api-key: ZtVdh8XQ2U8pWI2gmZ7f796Vh8GllXoN7mr0djNf

### GET request to list all proteins
GET http://localhost:8000/proteins HTTP/1.1
x-api-key: ZtVdh8XQ2U8pWI2gmZ7f796Vh8GllXoN7mr0djNf

### GET request to list all proteins
POST http://localhost:8000/order HTTP/1.1
x-api-key: ZtVdh8XQ2U8pWI2gmZ7f796Vh8GllXoN7mr0djNf

{
  "brothId": "1",
  "proteinId": "1"
}